const CONFIG = {
  ownerEmail: 'yani.wang@koreanskincare.com',
  historyFolderName: 'UX Cookbook – CS Insight History',
  senderName: 'UX Cookbook'
};

function setup() {
  const folder = getHistoryFolder_();
  console.log(`History folder: ${folder.getUrl()}`);
  return folder.getUrl();
}

function doGet() {
  const folderUrl = getHistoryFolder_().getUrl();
  const safeUrl = JSON.stringify(folderUrl);

  return HtmlService.createHtmlOutput(`
    <!doctype html>
    <html>
      <head>
        <base target="_top">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Opening CS insight history…</title>
      </head>
      <body>
        <p>Opening your private CS insight history…</p>
        <p><a href="${folderUrl}">Open Google Drive</a></p>
        <script>window.location.replace(${safeUrl});</script>
      </body>
    </html>
  `);
}

function doPost(event) {
  try {
    const payload = JSON.parse(event.postData.contents || '{}');

    if (payload.website) {
      return jsonResponse_({ ok: true });
    }

    const issue = cleanText_(payload.issue);
    if (!issue) {
      throw new Error('Complaint or issue is required.');
    }

    const files = Array.isArray(payload.files) ? payload.files : [];
    if (files.length > 5) {
      throw new Error('Upload no more than 5 files.');
    }

    const totalBytes = files.reduce((total, file) => total + Number(file.size || 0), 0);
    if (totalBytes > 20 * 1024 * 1024) {
      throw new Error('Supporting files must be 20 MB or less in total.');
    }

    const result = createInsightDocument_({
      issue,
      suggestion: cleanText_(payload.suggestion) || 'No suggested resolution provided.',
      evidenceContext: cleanText_(payload.evidenceContext) || 'No supporting context provided.',
      submittedAt: payload.submittedAt ? new Date(payload.submittedAt) : new Date(),
      files
    });

    sendOwnerNotification_(result);

    return jsonResponse_({
      ok: true,
      documentUrl: result.documentUrl
    });
  } catch (error) {
    console.error(error);
    return jsonResponse_({
      ok: false,
      error: error.message || 'The insight could not be processed.'
    });
  }
}

function createInsightDocument_(entry) {
  const historyFolder = getHistoryFolder_();
  const dateLabel = Utilities.formatDate(
    entry.submittedAt,
    Session.getScriptTimeZone(),
    'yyyy-MM-dd HH:mm'
  );
  const shortIssue = entry.issue.replace(/\s+/g, ' ').slice(0, 64);
  const title = `CS Insight – ${dateLabel} – ${shortIssue}`;
  const submissionFolder = historyFolder.createFolder(title);
  const uploadedFiles = [];

  entry.files.forEach(file => {
    const data = String(file.data || '').replace(/^data:[^;]+;base64,/, '');
    if (!data) return;

    const bytes = Utilities.base64Decode(data);
    const blob = Utilities.newBlob(
      bytes,
      file.type || 'application/octet-stream',
      safeFileName_(file.name || 'supporting-file')
    );
    const driveFile = submissionFolder.createFile(blob);
    uploadedFiles.push({
      name: driveFile.getName(),
      url: driveFile.getUrl()
    });
  });

  const document = DocumentApp.create(title);
  const documentFile = DriveApp.getFileById(document.getId());
  documentFile.moveTo(submissionFolder);

  const body = document.getBody();
  body.clear();
  body.appendParagraph('CS insight handoff')
    .setHeading(DocumentApp.ParagraphHeading.TITLE);
  body.appendParagraph(`Submitted ${dateLabel}`)
    .setForegroundColor('#5f6368');

  appendSection_(body, 'Complaint or issue', entry.issue);
  appendSection_(body, 'Suggested resolution', entry.suggestion);
  appendSection_(body, 'Supporting evidence', entry.evidenceContext);

  body.appendParagraph('Supporting files')
    .setHeading(DocumentApp.ParagraphHeading.HEADING1);

  if (!uploadedFiles.length) {
    body.appendParagraph('No files attached.');
  } else {
    uploadedFiles.forEach(file => {
      const paragraph = body.appendParagraph(`• ${file.name}`);
      paragraph.editAsText().setLinkUrl(file.url);
    });
  }

  body.appendHorizontalRule();
  body.appendParagraph('Generated by the UX Cookbook CS insight handoff.')
    .setForegroundColor('#5f6368')
    .setFontSize(9);
  document.saveAndClose();

  return {
    title,
    documentUrl: document.getUrl(),
    folderUrl: historyFolder.getUrl(),
    uploadedFiles
  };
}

function appendSection_(body, heading, content) {
  body.appendParagraph(heading)
    .setHeading(DocumentApp.ParagraphHeading.HEADING1);
  body.appendParagraph(content);
}

function sendOwnerNotification_(result) {
  const fileList = result.uploadedFiles.length
    ? `<p><strong>Supporting files:</strong> ${result.uploadedFiles.length}</p>`
    : '<p><strong>Supporting files:</strong> None</p>';

  MailApp.sendEmail({
    to: CONFIG.ownerEmail,
    subject: `New CS insight: ${result.title}`,
    name: CONFIG.senderName,
    body: [
      'A new CS insight document is ready.',
      '',
      `Document: ${result.documentUrl}`,
      `History folder: ${result.folderUrl}`
    ].join('\n'),
    htmlBody: `
      <p>A new CS insight document is ready.</p>
      ${fileList}
      <p><a href="${result.documentUrl}">Open the Google Doc</a></p>
      <p><a href="${result.folderUrl}">Open all CS insight history</a></p>
    `
  });
}

function getHistoryFolder_() {
  const properties = PropertiesService.getScriptProperties();
  const existingId = properties.getProperty('HISTORY_FOLDER_ID');

  if (existingId) {
    try {
      return DriveApp.getFolderById(existingId);
    } catch (error) {
      properties.deleteProperty('HISTORY_FOLDER_ID');
    }
  }

  const matchingFolders = DriveApp.getFoldersByName(CONFIG.historyFolderName);
  const folder = matchingFolders.hasNext()
    ? matchingFolders.next()
    : DriveApp.createFolder(CONFIG.historyFolderName);

  try {
    folder.addEditor(CONFIG.ownerEmail);
  } catch (error) {
    console.log(`Folder sharing did not need updating: ${error.message}`);
  }

  properties.setProperty('HISTORY_FOLDER_ID', folder.getId());
  return folder;
}

function cleanText_(value) {
  return String(value || '').trim().slice(0, 12000);
}

function safeFileName_(value) {
  return String(value).replace(/[\\/:*?"<>|]/g, '-').slice(0, 180);
}

function jsonResponse_(data) {
  return ContentService
    .createTextOutput(JSON.stringify(data))
    .setMimeType(ContentService.MimeType.JSON);
}
